# -*- coding: utf-8 -*-
"""SMSdetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MvBSeZOz-HT1hV6qLoDLfei8BjViPYuz
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("train.csv", encoding='latin-1')
df.head()

df['label'].value_counts()

import re
import nltk

nltk.download('stopwords')
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    words = text.split()
    words = [w for w in words if w not in stop_words]
    return " ".join(words)

df['clean_message'] = df['sms'].apply(clean_text)

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df['clean_message'])

y = df['label']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

nb = MultinomialNB()
lr = LogisticRegression(max_iter=1000)
svm = SVC()
rf = RandomForestClassifier()

models = {
    "Naive Bayes": nb,
    "Logistic Regression": lr,
    "SVM": svm,
    "Random Forest": rf
}

for name, model in models.items():
    model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, classification_report

for name, model in models.items():
    y_pred = model.predict(X_test)

    print(f"--- {name} ---")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    print()

import matplotlib.pyplot as plt
import numpy as np

# Données
models = ['Naive Bayes', 'Logistic Regression', 'SVM', 'Random Forest']
accuracy = [0.96, 0.96, 0.98, 0.98]
recall_spam = [0.72, 0.75, 0.87, 0.83]

x = np.arange(len(models))
width = 0.35

plt.figure()

plt.bar(x - width/2, accuracy, width, label='Accuracy')
plt.bar(x + width/2, recall_spam, width, label='Recall (Spam)')

plt.xticks(x, models)
plt.xlabel("Modèles")
plt.ylabel("Score")
plt.title("Comparaison des performances des modèles")

plt.legend()
plt.show()

